package com.king.app.jactionbar;

import android.content.Context;
import android.content.res.ColorStateList;
import android.content.res.TypedArray;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.graphics.drawable.ShapeDrawable;
import android.graphics.drawable.shapes.OvalShape;
import android.graphics.drawable.shapes.RectShape;
import android.support.v7.widget.ListPopupWindow;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.AttributeSet;
import android.util.TypedValue;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AccelerateDecelerateInterpolator;
import android.view.animation.AlphaAnimation;
import android.view.animation.Animation;
import android.view.animation.AnimationSet;
import android.view.animation.ScaleAnimation;
import android.view.animation.TranslateAnimation;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.king.app.jactionbar.conf.Constants;
import com.king.app.jactionbar.parser.MenuParser;
import com.king.app.jactionbar.utils.ParamUtils;

import org.xmlpull.v1.XmlPullParserException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 描述: 借鉴原生TitleBar的设计模式
 * 支持按照menu文件布局icon与文字列表，超出最大icon显示数量后以more菜单弹出列表显示
 * 扩展功能：
 * 1. 支持自定义icon大小，padding，以及标题文字大小
 * 2. 支持搜索模式（实现搜索按钮与搜索框动画以及keywords时间，搜索按钮自动适配位置）
 * 3. 支持confirm模式（cancel/ok）
 * <p/>作者：景阳
 * <p/>创建时间: 2018/3/27 16:10
 */
public class JActionbar extends RelativeLayout {

    /**
     * 集成icon的id
     */
    private final int ID_GROUP_TITLE = 1;
    private final int ID_GROUP_ICON = 2;
    private final int ID_ICON_SEARCH = 3;
    private final int ID_ICON_BACK = 4;
    private final int ID_ICON_MENU = 5;
    private final int ID_ICON_CLOSE_SEARCH = 6;
    private final int ID_CONFIRM_OK = 7;
    private final int ID_CONFIRM_CANCEL = 8;

    /**
     * icon size
     */
    private int iconSize = ParamUtils.dp2px(40);

    /**
     * icon padding
     */
    private int iconPadding = ParamUtils.dp2px(8);

    /**
     * support search icon and search input event
     */
    private boolean isSupportSearch = false;

    /**
     * ripple background color of icon
     */
    private int rippleColor = Color.parseColor("#66000000");

    /**
     * background of actionbar
     */
    private int backgroundColor;

    /**
     * max icon numbers to show
     */
    private int maxShowIcon = 4;

    /**
     * back
     */
    private ImageView ivBack;

    /**
     * more menu icon
     */
    private ImageView ivMenu;

    /**
     * title
     */
    private TextView tvTitle;

    /**
     * the group of all icons generated by menu
     */
    private LinearLayout groupMenu;

    /**
     * the group of confirm cancel or ok
     */
    private LinearLayout groupConfirm;

    /**
     * menu popup
     */
    private ListPopupWindow mPopup;

    /**
     * the group of search
     */
    private RelativeLayout groupSearch;

    /**
     * search icon
     * 只可能出现在最右侧或者倒数第二个位置
     */
    private ImageView ivSearch;

    /**
     * close search icon
     */
    private ImageView ivCloseSearch;

    /**
     * the action event of search keywords
     */
    private OnSearchListener onSearchListener;

    /**
     * the action event of each icon generated by menu item
     */
    private OnMenuItemListener onMenuItemListener;

    /**
     * the action event of back icon
     */
    private OnBackListener onBackListener;

    /**
     * confirm group关联的action id
     */
    private int mConfirmActionId;

    private OnConfirmListener onConfirmListener;

    /**
     * provider popup menu for icon menu
     */
    private PopupMenuProvider popupMenuProvider;

    /**
     * 下划线的颜色可以在JActionbar标签下通过theme属性设置style改变：android:theme="@style/EtActionSearch"
     *     <style name="EtActionSearch" parent="Theme.AppCompat.Light.NoActionBar">
     *         <item name="colorControlNormal">@color/white</item>
     *         <item name="colorControlActivated">@color/white</item>
     *     </style>
     */
    private EditText etSearch;

    /**
     * 通过MenuParser解析出来的menu元素
     */
    private JMenu menu;

    /**
     * 弹出列表菜单中的子项集合
     */
    private List<JMenuItem> moreItemList;

    private Map<Integer, Boolean> popupMenuMap;

    public JActionbar(Context context) {
        super(context);
        init(null);
    }

    public JActionbar(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(attrs);
    }

    private void init(AttributeSet attrs) {

        popupMenuMap = new HashMap<>();

        TypedArray typedArray = getContext().obtainStyledAttributes(attrs, R.styleable.JActionbar);
        rippleColor = typedArray.getColor(R.styleable.JActionbar_rippleColor, Color.parseColor("#66000000"));
        iconSize = typedArray.getDimensionPixelOffset(R.styleable.JActionbar_iconSize, ParamUtils.dp2px(40));
        iconPadding = typedArray.getDimensionPixelOffset(R.styleable.JActionbar_iconPadding, ParamUtils.dp2px(8));
        isSupportSearch = typedArray.getBoolean(R.styleable.JActionbar_supportSearch, false);
        backgroundColor = typedArray.getColor(R.styleable.JActionbar_android_background, Color.parseColor("#fa7198"));
        maxShowIcon = typedArray.getInt(R.styleable.JActionbar_maxShowIcon, 4);

        initTitle(typedArray);
        initMenu(typedArray);
    }

    /**
     * group title: include back icon and title text
     * @param a
     */
    private void initTitle(TypedArray a) {
        boolean showBack = a.getBoolean(R.styleable.JActionbar_showIconBack, true);
        String title = a.getString(R.styleable.JActionbar_title);
        int titleSize = a.getDimensionPixelOffset(R.styleable.JActionbar_titleSize, ParamUtils.dp2px(18));

        addTitle();
        ivBack.setVisibility(showBack ? VISIBLE:GONE);
        if (!showBack) {
            LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) tvTitle.getLayoutParams();
            params.leftMargin = ParamUtils.dp2px(16);
            tvTitle.setLayoutParams(params);
        }
        tvTitle.setTextSize(TypedValue.COMPLEX_UNIT_PX, titleSize);
        tvTitle.setText(title);
        tvTitle.setTextAppearance(getContext(), R.style.TvTitle);
    }

    /**
     * group menu: include all icons generated by menu resource
     * @param a
     */
    private void initMenu(TypedArray a) {
        groupMenu = new LinearLayout(getContext());
        groupMenu.setId(ID_GROUP_ICON);
        groupMenu.setOrientation(LinearLayout.HORIZONTAL);
        groupMenu.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);
        LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
        params.addRule(RelativeLayout.RIGHT_OF, ID_GROUP_TITLE);
        addView(groupMenu, params);

        int menuRes = a.getResourceId(R.styleable.JActionbar_menu, -1);
        if (menuRes != -1) {
            inflateMenu(menuRes);
        }
        else {
            showMenu();
        }
    }

    /**
     * add child views of title group
     */
    private void addTitle() {
        LinearLayout layout = new LinearLayout(getContext());
        layout.setId(ID_GROUP_TITLE);
        layout.setOrientation(LinearLayout.HORIZONTAL);
        layout.setGravity(Gravity.CENTER_VERTICAL);

        JMenuItem backItem = new JMenuItem();
        backItem.setId(ID_ICON_BACK);
        backItem.setIconRes(R.drawable.ic_back_white);
        ivBack = addIcon(backItem);
        ivBack.setOnClickListener(iconClickListener);
        layout.addView(ivBack);

        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        tvTitle = new TextView(getContext());
        tvTitle.setLayoutParams(params);
        tvTitle.setTextColor(Color.WHITE);
        layout.addView(tvTitle);

        LayoutParams rParams = new LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, LayoutParams.MATCH_PARENT);
        addView(layout, rParams);
    }

    /**
     * inflate menu from menu resource
     * @param menuRes
     */
    public void inflateMenu(int menuRes) {
        resetAllMenus();
        try {
            menu = new MenuParser().inflate(getContext(), menuRes);
            showMenu();
        } catch (XmlPullParserException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * 必须重置view的状态，否则会影响后续判断（比如ivMenu是否为null会影响search动画）
     */
    private void resetAllMenus() {
        groupMenu.removeAllViews();
        ivSearch = null;
        ivMenu = null;
    }

    /**
     * 1.最多允许显示maxShowIcon个icon，多余的以more展示
     * 2.如果支持搜索，icon大于maxShowIcon个->搜索按钮显示在more左边，否则显示在最右边
     * 3.search icon只会显示在最右边（icon总数小于等于maxShowIcon个）或者倒数第二个（icon总数大于maxShowIcon个）
     */
    private void showMenu() {
        int iconCount = 0;

        // never parsed xml or parsed with error
        if (menu == null) {
            menu = new JMenu();
        }

        List<JMenuItem> iconList = new ArrayList<>();
        moreItemList = new ArrayList<>();
        if (menu.getItemList() != null) {
            List<JMenuItem> list = menu.getItemList();
            for (JMenuItem item:list) {
                // 直接作为弹出菜单
                if (item.getShowAsAction() == Constants.SHOW_AS_ACTION_NEVER) {
                    moreItemList.add(item);
                }
                else {
                    iconList.add(item);
                }
            }
            iconCount += iconList.size();
        }

        // decide whether to add search icon
        JMenuItem searchIcon = null;
        if (isSupportSearch) {
            iconCount ++;
            searchIcon = new JMenuItem();
            searchIcon.setId(ID_ICON_SEARCH);
            searchIcon.setIconRes(R.drawable.ic_search_white);
            searchIcon.setTitle("Search");
            initSearch();
        }

        // decide which place should search icon be put in
        if (iconCount > maxShowIcon) {
            JMenuItem menuIcon = new JMenuItem();
            menuIcon.setId(ID_ICON_MENU);
            menuIcon.setIconRes(R.drawable.ic_more_vert_white);
            menuIcon.setTitle("Menu");
            if (searchIcon != null) {
                iconList.add(maxShowIcon - 2, searchIcon);
            }
            iconList.add(maxShowIcon - 1, menuIcon);
        }
        else {
            if (searchIcon != null) {
                iconList.add(searchIcon);
            }
        }

        // decide how many icons should be shown
        for (int i = 0; i < maxShowIcon && i < iconCount; i ++) {
            JMenuItem item = iconList.get(i);
            ImageView view = addIcon(item);
            if (view.getId() == ID_ICON_SEARCH) {
                ivSearch = view;
            }
            else if (view.getId() == ID_ICON_MENU) {
                ivMenu = view;
            }
            view.setOnClickListener(iconClickListener);
            groupMenu.addView(view);
        }
        // the left items need be shown as menu item
        if (iconCount > maxShowIcon) {
            for (int i = maxShowIcon; i < iconList.size(); i ++) {
                moreItemList.add(iconList.get(i));
            }
        }

        if (ivMenu == null && moreItemList.size() > 0) {
            JMenuItem menuIcon = new JMenuItem();
            menuIcon.setId(ID_ICON_MENU);
            menuIcon.setIconRes(R.drawable.ic_more_vert_white);
            menuIcon.setTitle("Menu");
            ivMenu = addIcon(menuIcon);
            ivMenu.setOnClickListener(iconClickListener);
            groupMenu.addView(ivMenu);
        }

        // popup list to show menu item
        if (moreItemList.size() > 0) {
            List<String> list = new ArrayList<>();
            for (int i = 0; i < moreItemList.size(); i ++) {
                list.add(moreItemList.get(i).getTitle());
            }

            ArrayAdapter<String> adapter = new ArrayAdapter<>(getContext(), android.R.layout.simple_spinner_dropdown_item, list);
            mPopup = new ListPopupWindow(getContext());
            mPopup.setAnchorView(ivMenu);
            mPopup.setAdapter(adapter);
            mPopup.setWidth(ParamUtils.dp2px(140));
            mPopup.setHeight(ListPopupWindow.WRAP_CONTENT);
            mPopup.setHorizontalOffset(-10);
            mPopup.setDropDownGravity(Gravity.END);
            // 设置为true可以防止展开后再点More按钮又弹出一次
            mPopup.setModal(true);
            mPopup.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    if (onMenuItemListener != null) {
                        onMenuItemListener.onMenuItemSelected(moreItemList.get(position).getId());
                    }
                    mPopup.dismiss();
                }
            });
        }
    }

    /**
     * add child views of search group: include EditText and close icon
     */
    private void initSearch() {
        groupSearch = new RelativeLayout(getContext());
        groupSearch.setBackgroundColor(backgroundColor);
        groupSearch.setVisibility(GONE);
        // group的宽度固定为在search icon的左边
        // 当search icon位于倒数第二个的时候，动画会执行从search icon的左边跟随search icon一起移动
        LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, LayoutParams.MATCH_PARENT);
        addView(groupSearch, params);

        etSearch = new EditText(getContext());
        etSearch.setTextColor(Color.WHITE);
        params = new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
        params.leftMargin = ParamUtils.dp2px(16);
        params.rightMargin = ParamUtils.dp2px(10);
        params.bottomMargin = ParamUtils.dp2px(5);
        etSearch.setLayoutParams(params);
        etSearch.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                if (onSearchListener != null) {
                    onSearchListener.onSearchWordsChanged(s.toString());
                }
            }

            @Override
            public void afterTextChanged(Editable s) {

            }
        });
        groupSearch.addView(etSearch);

        JMenuItem item = new JMenuItem();
        item.setId(ID_ICON_CLOSE_SEARCH);
        item.setIconRes(R.drawable.ic_close_white);
        params = new LayoutParams(iconSize, iconSize);
        params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
        params.addRule(RelativeLayout.CENTER_VERTICAL);
        ivCloseSearch = addIcon(item, params);
        ivCloseSearch.setOnClickListener(iconClickListener);
        groupSearch.addView(ivCloseSearch);

        // getWidth()必须在view完成布局后才有值
        post(new Runnable() {
            @Override
            public void run() {
                LayoutParams params = (LayoutParams) groupSearch.getLayoutParams();
                params.width = getWidth() - iconSize;
                groupSearch.setLayoutParams(params);
            }
        });
    }

    private ImageView addIcon(JMenuItem item) {
        return addIcon(item, null);
    }

    /**
     * control the style of all icons
     * @param item
     * @param params
     * @return
     */
    private ImageView addIcon(JMenuItem item, LayoutParams params) {
        ImageView view = new ImageView(getContext());
        view.setPadding(iconPadding, iconPadding, iconPadding, iconPadding);

        GradientDrawable gd = new GradientDrawable();
        gd.setColor(Color.TRANSPARENT);
        // 参数1：波纹颜色，参数2：常态下的背景，参数3：波纹限制边界
        RippleDrawable drawable = new RippleDrawable(ColorStateList.valueOf(rippleColor)
                , gd, new ShapeDrawable(new OvalShape()));
        view.setBackground(drawable);

        view.setId(item.getId());
        view.setTag(item);
        view.setImageResource(item.getIconRes());
        if (params == null) {
            LinearLayout.LayoutParams lParams = new LinearLayout.LayoutParams(iconSize, iconSize);
            view.setLayoutParams(lParams);
        }
        else {
            view.setLayoutParams(params);
        }
        return view;
    }

    /**
     * show cancel/ok actions
     * @param actionId
     */
    public void showConfirmStatus(int actionId) {
        mConfirmActionId = actionId;
        if (groupConfirm == null) {
            initGroupConfirm();
        }
        else {
            groupConfirm.setVisibility(VISIBLE);
        }
        groupMenu.setVisibility(GONE);
    }

    public void cancelConfirmStatus() {
        mConfirmActionId = 0;
        groupConfirm.setVisibility(GONE);
        groupMenu.setVisibility(VISIBLE);
    }

    public void setOnConfirmListener(OnConfirmListener onConfirmListener) {
        this.onConfirmListener = onConfirmListener;
    }

    private void initGroupConfirm() {
        LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.MATCH_PARENT);
        params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
        groupConfirm = new LinearLayout(getContext());
        groupConfirm.setLayoutParams(params);

        TextView view = addConfirmText(ID_CONFIRM_CANCEL, "Cancel");
        groupConfirm.addView(view);
        view = addConfirmText(ID_CONFIRM_OK, "Ok");
        groupConfirm.addView(view);

        addView(groupConfirm);
    }

    private TextView addConfirmText(int id, String text) {
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.MATCH_PARENT);
        TextView view = new TextView(getContext());
        view.setText(text);
        view.setId(id);
        view.setPadding(ParamUtils.dp2px(15), 0, ParamUtils.dp2px(15), 0);
        view.setTextColor(Color.WHITE);
        view.setGravity(Gravity.CENTER);
        view.setTextSize(TypedValue.COMPLEX_UNIT_PX, ParamUtils.dp2px(18));
        GradientDrawable gd = new GradientDrawable();
        gd.setColor(Color.TRANSPARENT);
        // 参数1：波纹颜色，参数2：常态下的背景，参数3：波纹限制边界
        RippleDrawable drawable = new RippleDrawable(ColorStateList.valueOf(rippleColor)
                , gd, new ShapeDrawable(new RectShape()));
        view.setBackground(drawable);
        view.setOnClickListener(iconClickListener);
        view.setLayoutParams(params);
        view.setTextAppearance(getContext(), R.style.TvTitle);
        return view;
    }

    private OnClickListener iconClickListener = new OnClickListener() {
        @Override
        public void onClick(View v) {
            switch (v.getId()) {
                case ID_ICON_BACK:
                    if (onBackListener != null) {
                        onBackListener.onBack();
                    }
                    break;
                case ID_ICON_SEARCH:
                    showSearchBar();
                    break;
                case ID_ICON_CLOSE_SEARCH:
                    hideSearchBar();
                    break;
                case ID_ICON_MENU:
                    mPopup.show();
                    break;
                case ID_CONFIRM_OK:
                    if (onConfirmListener == null) {
                        cancelConfirmStatus();
                    }
                    else {
                        if (onConfirmListener.onConfirm(mConfirmActionId)) {
                            if (!onConfirmListener.disableInstantDismissConfirm()) {
                                cancelConfirmStatus();
                            }
                        }
                    }
                    break;
                case ID_CONFIRM_CANCEL:
                    onCancel();
                    break;
                default:
                    if (popupMenuMap.get(v.getId()) != null && popupMenuMap.get(v.getId())) {
                        if (popupMenuProvider != null) {
                            popupMenuProvider.getPopupMenu(v.getId(), v).show();
                            return;
                        }
                    }
                    if (onMenuItemListener != null) {
                        onMenuItemListener.onMenuItemSelected(v.getId());
                    }
                    break;
            }
        }
    };

    private void onCancel() {
        if (onConfirmListener == null) {
            cancelConfirmStatus();
        }
        else {
            if (onConfirmListener.onCancel(mConfirmActionId)) {
                if (!onConfirmListener.disableInstantDismissCancel()) {
                    cancelConfirmStatus();
                }
            }
        }
    }

    private void showSearchBar() {
        if (groupSearch.getVisibility() != View.VISIBLE) {
            groupSearch.setVisibility(View.VISIBLE);
            // search处于倒数第二个位置
            if (ivMenu != null) {
                ivMenu.setVisibility(INVISIBLE);

                Animation iconAnim = new TranslateAnimation(0, ivSearch.getWidth(), 0, 0);
                iconAnim.setDuration(500);
                iconAnim.setFillAfter(true);
                ivSearch.startAnimation(iconAnim);

                AnimationSet set = new AnimationSet(true);
                set.setInterpolator(new AccelerateDecelerateInterpolator());
                Animation alpha = new AlphaAnimation(0, 1);
                alpha.setDuration(500);
                set.addAnimation(alpha);
                int startWidth = getWidth() - iconSize * 2;
                final int targetWidth = getWidth() - iconSize;
                float fs = (float) startWidth / (float) targetWidth;
                Animation scale = new ScaleAnimation(fs, 1, 1, 1);
                scale.setDuration(500);
                set.addAnimation(scale);
                groupSearch.startAnimation(set);
            }
            else {
                Animation animation = new AlphaAnimation(0, 1);
                animation.setDuration(500);
                animation.setInterpolator(new AccelerateDecelerateInterpolator());
                groupSearch.startAnimation(animation);
            }
        }
    }

    private void hideSearchBar() {
        // search处于倒数第二个位置
        if (ivMenu != null) {
            Animation iconAnim = new TranslateAnimation(ivSearch.getWidth(), 0, 0, 0);
            iconAnim.setDuration(500);
            ivSearch.startAnimation(iconAnim);

            Animation animation = new AlphaAnimation(1, 0);
            animation.setDuration(500);
            animation.setInterpolator(new AccelerateDecelerateInterpolator());
            animation.setAnimationListener(new Animation.AnimationListener() {
                @Override
                public void onAnimationStart(Animation animation) {

                }

                @Override
                public void onAnimationEnd(Animation animation) {
                    groupSearch.setVisibility(View.GONE);
                    ivMenu.setVisibility(VISIBLE);
                }

                @Override
                public void onAnimationRepeat(Animation animation) {

                }
            });
            groupSearch.startAnimation(animation);
        }
        else {
            Animation animation = new AlphaAnimation(1, 0);
            animation.setDuration(500);
            animation.setInterpolator(new AccelerateDecelerateInterpolator());
            animation.setAnimationListener(new Animation.AnimationListener() {
                @Override
                public void onAnimationStart(Animation animation) {

                }

                @Override
                public void onAnimationEnd(Animation animation) {
                    groupSearch.setVisibility(View.GONE);
                }

                @Override
                public void onAnimationRepeat(Animation animation) {

                }
            });
            groupSearch.startAnimation(animation);
        }
    }

    public void setOnSearchListener(OnSearchListener onSearchListener) {
        this.onSearchListener = onSearchListener;
    }

    public void setOnMenuItemListener(OnMenuItemListener onMenuItemListener) {
        this.onMenuItemListener = onMenuItemListener;
    }

    public void setOnBackListener(OnBackListener onBackListener) {
        this.onBackListener = onBackListener;
    }

    public void setTitle(String name) {
        tvTitle.setText(name);
    }

    public void enableSearch() {
        isSupportSearch = true;
    }

    public void setPopupMenuProvider(PopupMenuProvider popupMenuProvider) {
        this.popupMenuProvider = popupMenuProvider;
    }

    /**
     * 注册popupMenu
     * @param menuItemId
     */
    public void registerPopupMenu(int menuItemId) {
        popupMenuMap.put(menuItemId, true);
    }

    /**
     * 取消注册popupMenu
     * @param menuItemId
     */
    public void removeRegisteredPopupMenu(int menuItemId) {
        popupMenuMap.remove(menuItemId);
    }

    public boolean onBackPressed() {
        if (mConfirmActionId != 0) {
            onCancel();
            return true;
        }
        return false;
    }
}
